### ISSUE TITLE
Player Events?

### ISSUE THREAD

**Issue by chrismatthieu** [msub2/aframe-exokit-avatars#2]
This may be an exokit question but do the hands and head and player position emit events when moving? I would like to bootstrap a multi-player demo in AFrame using VRMs.

**Comment by msub2** [comment]
They do not, I believe in the original exokit avatars example scene avaer set it up to update the rig info across an RTC connection every 50 ms. You can reference [this section](https://github.com/exokitxr/avatars/blob/master/index.html#L1343) of the original example to get a feel for how he did it.
